cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv
dist: xenial
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
    - PYENV_ROOT="$HOME/.pyenv"
    - PATH="$PYENV_ROOT/bin:$PATH"
    - PIP_CACHE_DIR="$HOME/.cache/pip"  # unify pip cache location for all platforms
stages:
#  - check
#  - test
  - build
# Travis doesn't support testing python on Mac yet, so we need
# to workaround it by installing it directly with brew.
#
# Note that we specify language as ruby-2.4.3 to help us satisfy
# fpm dependencies, as travis runs el capitan with an old ruby
# version, that causes fpm to crash.
#
# Each job will use the previous job's `stage` tag if not specified.
jobs:
  include:
  # patch formatting checks
#  - name: "Check patch formatting"
#    stage: check
#    os: linux
#    language: python
#    python: 3.7
#    before_install:
#    install:
#    script: ./scripts/ci/check_patch.sh
  # test jobs
#  - name: "3.7 on Windows"
#    stage: test
#    os: windows           # Windows 10.0.17134 N/A Build 17134
#    language: shell       # 'language: python' is an error on Travis CI Windows
#  - name: "3.5 on Linux"
#    language: python
#    python: 3.5
#  - name: "3.6 on Linux"
#    language: python
#    python: 3.6
#  - name: "3.7 on Linux"
#    language: python
#    python: 3.7
#  - name: "3.7 on Mac"
#    os: osx
#    osx_image: xcode11.3
  # build jobs
  - name: "Pypi pkgs"
    if: tag is present
    stage: build
    language: python
    python: 3.7
    script: ./scripts/build_package.sh
    deploy:
    - provider: pypi
      user:
        secure: "SCKMf0Z3NrkJS/1Rj4FiqEFuwcKwD4ismzZqPh+LSyVyA3Owsf7Ihen22RvPWUXHYQK269lx7vYibwIuNAA+FJewHKT9zeoacSOvJCNXDBNIjkZErukRwAADxVbpccZoZWRErC6iTtgPEoTlI2LcG9TuwXBlx0QO6+LZv+tjdEla5q6qMfjP0H60J+EZ2lLYEDY6l8Nzrd+cFLXK93bIwrInkDBmSiZHnUYJyjrPQoZQaD/uSJjuWTbtWr40Vz2RjKU6sjre7pPEzXJ1EzYKeuZoHr+EcRhqVjqGnjVCeyKbUZPcgEgwDYaGpfn/J7++6O68pN1KjXUQ0WTZbJMkLFvt2iX8TGv3U62Sw6EI2uLXkRPuHUZb2pbx3hhmbOZvTdR2m8cGdNyKkXMJQLVDiQCgWSvvbNMNdNhaOCpJNESAiDWbXn69tlk8mlf/E59znkJN/aDHTxLCFBD4D7BPwI2wvz2t8DXi/lSXz8iy+D7FdieygZm17TjM/n9lzjfSzqLVui0k5Bcco9cbgd/HKcyvfyNT5S2H1QnB4KzjNCDKp/yk2TN3lnMA4j3CGL8nycrZRLTxsCcHIBoYTmWlnBF3qg3/4IkqL9ZyRvbkyd+NCWAqmEv2udiVk44M53dfgV1ImVCoN/shfahctNoySKKiWn8obaf2p6gikdITyLI="
      password:
        secure: "gtBOX2dIXIKx82DcmgQF1C35CK399aTzIgovXqSNhdAc9ROnxU/j4I5LK220lOUCUCMXPF6czlt04XRjkKK4o0BvaqFQXasbud0IKLV4Fup3Fc2jcMybo4IB0AkmKgTu7nYdZiMORoWCMA5ysVyG/TEWm65i66h//col6IbuosuRtb2UddZ+7JHwVgfyjqO463QYtdGweCHWiOPlzSq9F61A4flPgzrkeNCIGOIA4APrBbNUBwf9dnUY4fFPdCXhYJd35n1zJA3PXd6rfBgCptZONn5ObuhZM4Mj/V2urRRxcPT5v3iwIZrmwxLXoV+OY4ym7FunyhVoSEjVivqWO1PVyuw6x/7FUL6ojZTzPpdyj7VXUyuVBMgtfAmtWuBygfvoY2St2lP8DLRX/EUiJCPIZHMXjFEbBZ0PG3SBVvOoKFL8VgTJzX/cZlTa1kIFCaxAv60u5pXiHuhrvfKvIQDKzkx6uXGxTbOHyp+s/yJoQoe5EiLNwKMZq9VWN91kSkVPSzUXCnRl3H/WxCQLWxckjQJEtxZB8bHPItX+MZRzazmng3K/rY7ECA6/obl+0SOrJMOxdKQeNdNLA5myYU1SesGw9d+V6SZZfhyTN+221UVQI1KpfAPpI2rmGDYalQzjJBPbH8rF837uYw7XdwA31qEobh2Ldke8CdOErUE="
      skip_existing: true
      file_glob: true
      file:
        - dist/pydrive2*.whl
        - dist/pydrive2*.tar.gz
      skip_cleanup: true
      on:
        tags: true
        repo: iterative/PyDrive2

before_install:
  - bash ./scripts/ci/before_install.sh
  - source env.sh
  - bash ./scripts/ci/check_python.sh
install:
  - bash ./scripts/ci/install.sh
script:
  - bash ./scripts/ci/script.sh
